version: "3.8"

services:
  chat_api:
    build: .
    container_name: chat_api
    command: >
      bash -c 
      "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - chat_redis
      - chat_db
    networks:
      - chat_network
  chat_redis:
    image: redis:7.0-alpine
    container_name: chat_redis
    networks:
      - chat_network
  chat_db:
    image: docker.io/postgres:15.1-alpine
    container_name: chat_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - chat_pgdata:/var/lib/postgresql/data/
    networks:
      - chat_network

volumes:
  chat_pgdata:

networks:
  chat_network:
    driver: bridge